---
title: "Client Report - New York Crashes"
subtitle: "Course DS 460"
author: "Joel Doh"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import pins
import plotly.express as px
from lets_plot import *
LetsPlot.setup_html()
```


## Elevator pitch

_Around the so many accidents happening in New York, there facts that we can analyze through data. Those facts include when most accidents happen and how people get injured from them. In this project, we are going to analyze those facts by querying ny_crashes dataset and commenting the outcome._

```{python}
dat = pl.read_parquet("ny_crashes.parquet")
print(dat.head(5))
```

__Highlight the Questions and Tasks__

## QUESTION|TASK 1

__Compare the accident and injury rates per hour.__

_We can see that even the rates of accidents is pretty high at 11am, for the part there are more accidents between 1pm to 6pm included. Also, the rate of injured people is high around that range. That is likely due to many people heading to lunch or coming back from lunch or work, which may increase traffic on the road and the number people trying to hurry to their destinations. However, though there is lower accident rate after 6pm, the number of people injured is high compared to the number of accidents. This can be explained by many people getting rides in a single car, especially young people going to party, or families going to dinner in restaurants._

```{python}
rate_hour = dat\
    .with_columns(pl.col("date_time").dt.truncate("1h").alias("hour_floor"))\
    .group_by("hour_floor")\
    .agg(
        pl.col("NUMBER OF PERSONS INJURED").sum().alias("injured_total"),
        pl.col("BOROUGH").count().alias("accident_count")
    )
rate_hour=rate_hour.select(pl.col('hour_floor').dt.hour().alias('hours'), 
                 pl.col('injured_total','accident_count'))
rate_hour=rate_hour.unique('hours')
print(rate_hour)
```


```{python}
acc_hr_chart = px.bar(rate_hour, x='hours', y='accident_count', color='hours', title='Accident Rate per Hour', orientation='v')
print(acc_hr_chart.show())
```


```{python}
inj_hr_chart = px.bar(rate_hour, x='hours', y='injured_total', color='hours', title='Rate of People Injured per Hour')
print(inj_hr_chart.show())

```


## QUESTION|TASK 2

__Compare the accident and injury rates per day.__

_When comparing the the rate of accidents and injured people per day, the most striking observation is how Sunday does in this comparison. Sunday has the smallest accident rate, but the highest number of people injured. We can explain this by families using a single car to go to church or family gatherings. Midweeks (Wednesdays) and weekends(Fridays and Saturdays) have also high accident and injury rates._

```{python}
rate_day = dat\
    .with_columns(pl.col("date_time").dt.truncate("1d").alias("day_floor"))\
    .group_by("day_floor")\
    .agg(
        pl.col("NUMBER OF PERSONS INJURED").sum().alias("injured_total"),
        pl.col("BOROUGH").count().alias("accident_count"))\
    .with_columns(pl.col("day_floor").dt.weekday().alias("weekday"),
    pl.col("day_floor").dt.strftime('%A').alias('days'))
    
rate_day=rate_day.unique('weekday').sort('weekday', descending=False)
print(rate_day)
```


```{python}
acc_dy_chart = px.bar(rate_day, x='days', y='accident_count', color='days', title='Accident Rate per Day', orientation='v')
acc_dy_chart
```


```{python}
inj_dy_chart = px.bar(rate_day, x='days', y='injured_total', color='days', title='Rate of People Injured per Day')
inj_dy_chart
```
